### PR TITLE
Closes #23 - address VNode API changes from {tag,data,children} to {t…

### LINKED ISSUE #23: Cannot read property 'class' of undefined
Not sure if this was reported and/or discussed before, but with latest hyperapp (0.14.0) and latest picostyle (0.1.5) I am noticing this error:

image

Here is a codepen for repro - https://codepen.io/abhishekisnot/pen/XeENxo

I will try to get to this later, reporting here if anyone else gets to it earlier.

### PR DESCRIPTION
**Pull request by osdevisnot**
…ag,props,children}

### CODE REVIEW

**Comment by osdevisnot** [comment]
@morishitter no rush, but this is currently breaking one of our starter kit deployments -- http://hyperapp-fusebox.deployable.site/

**Comment by morishitter** [comment]
@osdevisnot SGTM 👍

**Comment by osdevisnot** [comment]
@morishitter thank you, but it seems the latest publish does not have these changes on NPM. Maybe we need to run build before npm publish?

**Comment by JorgeBucaran** [comment]
Before you publish, you should also update `.tag` to `.type` to be compatible with 0.15.0.

This wouldn't be a problem if you use the `h()` function to create the VNode instead of editing it directly.

**Comment by osdevisnot** [comment]
@JorgeBucaran Not sure I am following, I don't see where picostyle is using `.tag`.  

@morishitter Not sure if this is intentional, but it seems the current merge strategy is little incorrect. Here is the list of generated classes for some of my use cases: (notice repeating `p1` and `stat` classes)

image

The repeating `stat` class is when I already have class declaration on my element:
```
const Button = ({ kind, label, update, disabled }) => (
  <StyledButton
    class="stat"
    kind={kind}
    onclick={update}
    disabled={disabled ? disabled : false}
  >
    {label}
  </StyledButton>
)
```

and multiple class names is where I am composing  nodes:
```
export const Heading = styled('h1')({ color: '#111' })
export const PaddedHeading = styled(Heading)({ padding: '1rem 0' })
```

**Comment by JorgeBucaran** [comment]
@osdevisnot You are right, it's not so you are safe! If it was using it, though, it would need to change to `.type` since the VNode API changed in 0.15.0.

Okay, then LGTM

**Comment by morishitter** [comment]
@osdevisnot 

>  it seems the latest publish does not have these changes on NPM in 0.1.6 version. Maybe we need to run build before npm publish?

Sorry, I just released v0.1.7 🚀

**Pull request merged**
