### PR TITLE
don't pass data to decls if it's not a fn

### PR DESCRIPTION
**Pull request by VinSpee**
resolves the issue introduced in #15

### CODE REVIEW

**Comment by VinSpee** [comment]
like so @morishitter?

**Comment by morishitter** [comment]
@VinSpee Thank you for your fast support. It seems to work well with the current [example](https://github.com/picostyle/picostyle/blob/master/examples/hyperapp/app.js).

@JorgeBucaran Is that OK for you?

**Comment by VinSpee** [comment]
no problem sorry for the mistake!

**Comment by JorgeBucaran** [comment]
@morishitter Up to you bro.

**Comment by morishitter** [comment]
I merge this PR because a bug includes in https://github.com/picostyle/picostyle/pull/15 is fixed.

**Comment by morishitter** [comment]
@VinSpee I just released v0.1.3 includes this changes. Thank you for your help :)

**Pull request merged**
